# Generated by Django 3.0.5 on 2020-10-31 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='vacio', max_length=100, null=True)),
                ('slug', models.CharField(default='vacio', max_length=100, null=True)),
                ('detalle', models.TextField(null=True)),
                ('fecha', models.DateField()),
                ('categorias', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.Categorias')),
            ],
            options={
                'db_table': 'post',
                'managed': True,
            },
        ),
    ]
